// Auto-generated by scripts/fetch-free-models.js
// Last updated: 2026-02-06T13:55:03.930Z
// Total models: 25
// API Source: https://openrouter.ai/api/v1/models
// Web URL: https://openrouter.ai/models/?fmt=cards&input_modalities=text&order=top-weekly&q=free&output_modalities=text
//
// DO NOT EDIT THIS FILE MANUALLY
// To update: run `node scripts/fetch-free-models.js`

const FREE_MODEL_CHAIN = [
  {
    id: 'qwen/qwen3-next-80b-a3b-instruct:free',
    name: 'Qwen: Qwen3 Next 80B A3B Instruct (free)',
    description: '262k context. Free tier.',
    contextWindow: 262144
  },
  {
    id: 'qwen/qwen3-coder:free',
    name: 'Qwen: Qwen3 Coder 480B A35B (free)',
    description: '262k context. Free tier.',
    contextWindow: 262000
  },
  {
    id: 'stepfun/step-3.5-flash:free',
    name: 'StepFun: Step 3.5 Flash (free)',
    description: '256k context. Free tier.',
    contextWindow: 256000
  },
  {
    id: 'nvidia/nemotron-3-nano-30b-a3b:free',
    name: 'NVIDIA: Nemotron 3 Nano 30B A3B (free)',
    description: '256k context. Free tier.',
    contextWindow: 256000
  },
  {
    id: 'tngtech/tng-r1t-chimera:free',
    name: 'TNG: R1T Chimera (free)',
    description: '164k context. Free tier.',
    contextWindow: 163840
  },
  {
    id: 'tngtech/deepseek-r1t2-chimera:free',
    name: 'TNG: DeepSeek R1T2 Chimera (free)',
    description: '164k context. Free tier.',
    contextWindow: 163840
  },
  {
    id: 'deepseek/deepseek-r1-0528:free',
    name: 'DeepSeek: R1 0528 (free)',
    description: '164k context. Free tier.',
    contextWindow: 163840
  },
  {
    id: 'tngtech/deepseek-r1t-chimera:free',
    name: 'TNG: DeepSeek R1T Chimera (free)',
    description: '164k context. Free tier.',
    contextWindow: 163840
  },
  {
    id: 'arcee-ai/trinity-mini:free',
    name: 'Arcee AI: Trinity Mini (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'openai/gpt-oss-120b:free',
    name: 'OpenAI: gpt-oss-120b (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'openai/gpt-oss-20b:free',
    name: 'OpenAI: gpt-oss-20b (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'z-ai/glm-4.5-air:free',
    name: 'Z.AI: GLM 4.5 Air (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'meta-llama/llama-3.2-3b-instruct:free',
    name: 'Meta: Llama 3.2 3B Instruct (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'nousresearch/hermes-3-llama-3.1-405b:free',
    name: 'Nous: Hermes 3 405B Instruct (free)',
    description: '131k context. Free tier.',
    contextWindow: 131072
  },
  {
    id: 'arcee-ai/trinity-large-preview:free',
    name: 'Arcee AI: Trinity Large Preview (free)',
    description: '131k context. Free tier.',
    contextWindow: 131000
  },
  {
    id: 'upstage/solar-pro-3:free',
    name: 'Upstage: Solar Pro 3 (free)',
    description: '128k context. Free tier.',
    contextWindow: 128000
  },
  {
    id: 'nvidia/nemotron-nano-9b-v2:free',
    name: 'NVIDIA: Nemotron Nano 9B V2 (free)',
    description: '128k context. Free tier.',
    contextWindow: 128000
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct:free',
    name: 'Meta: Llama 3.3 70B Instruct (free)',
    description: '128k context. Free tier.',
    contextWindow: 128000
  },
  {
    id: 'qwen/qwen3-4b:free',
    name: 'Qwen: Qwen3 4B (free)',
    description: '41k context. Free tier.',
    contextWindow: 40960
  },
  {
    id: 'liquid/lfm-2.5-1.2b-thinking:free',
    name: 'LiquidAI: LFM2.5-1.2B-Thinking (free)',
    description: '33k context. Free tier.',
    contextWindow: 32768
  },
  {
    id: 'liquid/lfm-2.5-1.2b-instruct:free',
    name: 'LiquidAI: LFM2.5-1.2B-Instruct (free)',
    description: '33k context. Free tier.',
    contextWindow: 32768
  },
  {
    id: 'cognitivecomputations/dolphin-mistral-24b-venice-edition:free',
    name: 'Venice: Uncensored (free)',
    description: '33k context. Free tier.',
    contextWindow: 32768
  },
  {
    id: 'google/gemma-3n-e2b-it:free',
    name: 'Google: Gemma 3n 2B (free)',
    description: '8k context. Free tier.',
    contextWindow: 8192
  },
  {
    id: 'google/gemma-3n-e4b-it:free',
    name: 'Google: Gemma 3n 4B (free)',
    description: '8k context. Free tier.',
    contextWindow: 8192
  },
  {
    id: 'openrouter/free',
    name: 'OpenRouter Free Router',
    description: 'Selects random free model. Final fallback.',
    contextWindow: 8000
  }
];

// Export for browser usage
if (typeof window !== 'undefined') {
  window.FREE_MODEL_CHAIN = FREE_MODEL_CHAIN;
}
